name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Configure Project
        uses: threeal/cmake-action@v2.1.0
        with:
          run-build: false

      - name: Install Project
        run: cmake --install build --prefix install
