name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-project:
    name: Test Project
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-24.04, macos-14]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.2.0
        with:
          version: 6.2.4
          cache: true

      - name: Configure Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: SETUP_QT_ENABLE_TESTS=ON
          run-build: false

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: debug
          verbose: true
